<?php
/**
 * AuthApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  DiginizeVereinsfliegerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vereinsflieger REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 466.98009
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DiginizeVereinsfliegerApi;

use \DiginizeVereinsfliegerApi\Configuration;
use \DiginizeVereinsfliegerApi\ApiException;
use \DiginizeVereinsfliegerApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  DiginizeVereinsfliegerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAccesstoken
     *
     * .
     *
     */
    public function testGetAccesstoken()
    {
    }

    /**
     * Test case for getUser
     *
     * .
     *
     */
    public function testGetUser()
    {
    }

    /**
     * Test case for signin
     *
     * .
     *
     */
    public function testSignin()
    {
    }

    /**
     * Test case for signout
     *
     * .
     *
     */
    public function testSignout()
    {
    }
}
