<?php
/**
 * ExtendedUserDtoTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DiginizeVereinsfliegerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vereinsflieger REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 466.98009
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DiginizeVereinsfliegerApi;

use PHPUnit\Framework\TestCase;

/**
 * ExtendedUserDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ExtendedUserDto
 * @package     DiginizeVereinsfliegerApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExtendedUserDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ExtendedUserDto"
     */
    public function testExtendedUserDto()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "careof"
     */
    public function testPropertyCareof()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "zipcode"
     */
    public function testPropertyZipcode()
    {
    }

    /**
     * Test attribute "town"
     */
    public function testPropertyTown()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "birthday"
     */
    public function testPropertyBirthday()
    {
    }

    /**
     * Test attribute "birthplace"
     */
    public function testPropertyBirthplace()
    {
    }

    /**
     * Test attribute "homenumber"
     */
    public function testPropertyHomenumber()
    {
    }

    /**
     * Test attribute "mobilenumber"
     */
    public function testPropertyMobilenumber()
    {
    }

    /**
     * Test attribute "phonenumber"
     */
    public function testPropertyPhonenumber()
    {
    }

    /**
     * Test attribute "phnenumber2"
     */
    public function testPropertyPhnenumber2()
    {
    }

    /**
     * Test attribute "carlicenseplate"
     */
    public function testPropertyCarlicenseplate()
    {
    }

    /**
     * Test attribute "identification"
     */
    public function testPropertyIdentification()
    {
    }

    /**
     * Test attribute "natoid"
     */
    public function testPropertyNatoid()
    {
    }

    /**
     * Test attribute "policecert_validto"
     */
    public function testPropertyPolicecertValidto()
    {
    }

    /**
     * Test attribute "ice_contact1"
     */
    public function testPropertyIceContact1()
    {
    }

    /**
     * Test attribute "ice_contact2"
     */
    public function testPropertyIceContact2()
    {
    }

    /**
     * Test attribute "memberid"
     */
    public function testPropertyMemberid()
    {
    }

    /**
     * Test attribute "memberbegin"
     */
    public function testPropertyMemberbegin()
    {
    }

    /**
     * Test attribute "memberend"
     */
    public function testPropertyMemberend()
    {
    }

    /**
     * Test attribute "lettertitle"
     */
    public function testPropertyLettertitle()
    {
    }

    /**
     * Test attribute "memberstatus"
     */
    public function testPropertyMemberstatus()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "bankaccountname"
     */
    public function testPropertyBankaccountname()
    {
    }

    /**
     * Test attribute "directdebitauth"
     */
    public function testPropertyDirectdebitauth()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
    }

    /**
     * Test attribute "mandate"
     */
    public function testPropertyMandate()
    {
    }

    /**
     * Test attribute "mandatedate"
     */
    public function testPropertyMandatedate()
    {
    }

    /**
     * Test attribute "mailrecipient"
     */
    public function testPropertyMailrecipient()
    {
    }

    /**
     * Test attribute "roles"
     */
    public function testPropertyRoles()
    {
    }

    /**
     * Test attribute "sector"
     */
    public function testPropertySector()
    {
    }

    /**
     * Test attribute "functions"
     */
    public function testPropertyFunctions()
    {
    }

    /**
     * Test attribute "educations"
     */
    public function testPropertyEducations()
    {
    }
}
