<?php
/**
 * VereinsfliegerExtendedErrorDtoTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DiginizeVereinsfliegerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vereinsflieger REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 466.98009
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DiginizeVereinsfliegerApi;

use PHPUnit\Framework\TestCase;

/**
 * VereinsfliegerExtendedErrorDtoTest Class Doc Comment
 *
 * @category    Class
 * @description VereinsfliegerExtendedErrorDto
 * @package     DiginizeVereinsfliegerApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VereinsfliegerExtendedErrorDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VereinsfliegerExtendedErrorDto"
     */
    public function testVereinsfliegerExtendedErrorDto()
    {
    }

    /**
     * Test attribute "httpstatuscode"
     */
    public function testPropertyHttpstatuscode()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "accesstoken"
     */
    public function testPropertyAccesstoken()
    {
    }

    /**
     * Test attribute "phpsessid"
     */
    public function testPropertyPhpsessid()
    {
    }

    /**
     * Test attribute "urlpath"
     */
    public function testPropertyUrlpath()
    {
    }

    /**
     * Test attribute "urlfile"
     */
    public function testPropertyUrlfile()
    {
    }

    /**
     * Test attribute "passphrase"
     */
    public function testPropertyPassphrase()
    {
    }
}
