<?php
/**
 * VereinsfliegerResponseDtoTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DiginizeVereinsfliegerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vereinsflieger REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 466.98009
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DiginizeVereinsfliegerApi;

use PHPUnit\Framework\TestCase;

/**
 * VereinsfliegerResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description VereinsfliegerResponseDto
 * @package     DiginizeVereinsfliegerApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VereinsfliegerResponseDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VereinsfliegerResponseDto"
     */
    public function testVereinsfliegerResponseDto()
    {
    }

    /**
     * Test attribute "httpstatuscode"
     */
    public function testPropertyHttpstatuscode()
    {
    }
}
